[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-xperms"
version = "1.0.1"
dependencies = [
    "typing_extensions>=4.0",
    "endstone-jwplaceholderapi @ https://github.com/junggamyeon/JWPlaceholderAPI.git"
]
authors = [
    { name = "CYooBin10" },
]
description = "Lightweight permission, rank & prefix plugin for Endstone (Bedrock)"
requires-python = ">=3.10"

[tool.hatch.metadata]
allow-direct-references = true

[project.optional-dependencies]
dev = ["endstone", "ruff"]

[project.entry-points."endstone"]
xperms = "endstone_xperms:XPermsPlugin"
